spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/newsdata
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

gnews:
  api-key: 0e90b195822201e20ce6b26e82b21162

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
