version: "3.8"

services:
  springboot-backend:
    build:
      context: ./Personalized-News-Recommender-System
    container_name: news-backend
    ports:
      - "8080:8080"
    depends_on:
      - fastapi-ml
    restart: always  
    networks:
      - newsnet

  fastapi-ml:
    build:
      context: ./News-Recommender-ML
    container_name: ml-service
    ports:
      - "8000:8000"
    networks:
      - newsnet

  react-frontend:
    build:
      context: ./news-recommneder-frontend
    container_name: react-ui
    ports:
      - "3000:80"
    depends_on:
      - springboot-backend
    networks:
      - newsnet

networks:
  newsnet:
    driver: bridge
