name: CI/CD Pipeline for Personalized News Recommender

on:
  push:
    branches: [ main ]

env:
  IMAGE_BACKEND: sumitranaware24/personalizednewsrecommenderapp-springboot-backend:v5
  IMAGE_FRONTEND: sumitranaware24/personalizednewsrecommenderapp-react-frontend:latest
  IMAGE_ML: sumitranaware24/personalizednewsrecommenderapp-fastapi-ml:latest
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Spring Boot backend
      run: |
        docker build -t $IMAGE_BACKEND ./Personalized-News-Recommender-System
        docker push $IMAGE_BACKEND

    - name: Build and push React frontend
      run: |
        docker build -t $IMAGE_FRONTEND ./news-recommneder-frontend
        docker push $IMAGE_FRONTEND

    - name: Build and push FastAPI ML service
      run: |
        docker build -t $IMAGE_ML ./News-Recommender-ML
        docker push $IMAGE_ML

    - name: Deploy Spring Boot backend to Render
      run: |
        curl -X POST ${{ secrets.RENDER_SERVICE_BACKEND }}

    - name: Deploy React frontend to Render
      run: |
        curl -X POST ${{ secrets.RENDER_SERVICE_FRONTEND }}

    - name: Deploy ML Service to Render
      run: |
        curl -X POST ${{ secrets.RENDER_SERVICE_ML }}
